### ISSUE TITLE
SyneditTextBuffer.LoadFromStream - forced UTF-8

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#101]
I don't like a way how SynEditTextBuffer.LoadFromStream is implemented.
If there is Ansi encoding, hard check of UTF-8 is made.
This prevent you load in encoding you want. 

**Example:** 
you have export from MySQL DB, very often mixed national ANSI characters with UTF-8.
stream is detected as UTF-8, but load from stream fails, due to non encoded national characters. One UTF-8 encoded char can break loading.

There is more possible ways how to handle it, e.g. add property which allows you to skip this test, add another LoadFromStream() method.

**Comment by pyscripter** [comment]
- If you know the encoding then set the DefaultEncoding property of LInes.  If it finds a BOM it will use the encoding related to the BOM otherwise the Default encoding will be used.
- If no then SynEdit has to guess.
  - It uses Ansi
  - If DetectUTF8 is set it then checks whether the text contains utf8 characters.

What is wrong with the above?
Utf8 without BOM is the default in many programming languages and data files (e.g. python, json)

**Comment by JaFi-cz** [comment]
Sorry, I overlooked DetectUTF8 property. This is exacly what I am looking for.
Sorry for stupid request.
