### ISSUE TITLE
Missing TSynEditDocumentManager

### ISSUE THREAD

**Issue by vincentparrett** [TurboPack/SynEdit#202]
Where is TSynEditDocumentManager manager in this project? Was it just not synced over from the original repo or was it removed intentionally?

I was excited to try some of the new features here, but I rely heavily on the documentmanager (which I originally contributed) to manage multiple documents with a single editor control.

**Comment by vincentparrett** [comment]
It looks like this was never copied across from the original project - which is a pity since it now not so easy to implement.

This is the original
https://github.com/SynEdit/SynEdit/blob/master/Source/SynEditDocumentManager.pas

It works by saving/restoring the editor state (caret, highligher, undo/redo) when switching documents - I guess that is a bit more involved now as there is more state to track.

**Comment by pyscripter** [comment]
The purpose of the unit is to serve a specific type of applications that has a single SynEdit and manage/display multiple documents with that single SynEdit, storing and restoring state when you switch documents.  But the unit has limitations:

- It stores the content in a standard TStingList.   The  SynEdit TSynEditStringList has more information that is not stored/restored including the line modification state of different lines.
- What is defined as state is narrow and quite limiting.  For example the caret position is stored but not the selection.
- In addition, depending on the application, there may be other document specific, properties which are not stored/restored (indicators and spelling errors come to mind).
- Also if you deal with large files, storing and restoring the content, the undo etc. will be slow.   A better approach may be for TSynDocument to store the whole SynEdit component and when you change documents you just hide/show a given SynEdit.
- The demos demonstrate a different interfaced based approach that can work with a single document, tabbed document and MDI style of applications, which is more comprehensive.

I suppose the unit could go into an Extras (as VirtualTrees does), so that users can use the unit directly or adapt it to their needs.

**Comment by vincentparrett** [comment]
The unit was written a long time ago.. when Synedit was a lot simpler.  Not sure why it was working agains SynMemo either.. or why I was using that rather than plain TSynEdit... was a long time ago now.    

Note there is a good reason to use this technique though, and that is saving resources/memory. SynEdit is quite a heavy control.. using a single instance of the control is worthwhile in some instances. 

After looking at this version of synedit, it looks like it's going to be difficult to replicate without modifying TSynEdit, as the undo/redo etc is not exposed in a way it could be saved/restored. Some form of state management would be needed. I'll have a look at it.. I really would like to benefit from the new synedit features.. but need to be able to do this, otherwise I'm rewriting a ton of other code.

**Comment by pyscripter** [comment]
> Note there is a good reason to use this technique though, and that is saving resources/memory. SynEdit is quite a heavy control.. using a single instance of the control is worthwhile in some instances.

Agree partially, but if you store all the memory-heavy contents (text, undo redo etc.)  the rest does not take much memory.

**Comment by vincentparrett** [comment]
Probably not.. but there are other reasons.. in my scenario each document could be a different language with a different highlighter.. so using this technique I only use 1 highlighter per language (since only one script is visible at at time). Some of the state isn't important to maintain, like selection. 

I guess I need to evaluate what I need to do, either implementing the document manager (lots of unplanned work by the looks of it) or implement multiple synedits in my code (also lots of unplanned work) - or just stick with the orgininal synedit. I do wish this fork was never done - it was unnecessary on an active project - but that's history now.

**Comment by pyscripter** [comment]
> I only use 1 highlighter per language

You can use the same highlighter in multiple SynEdits anyway
