### ISSUE TITLE
SyneditHighlighter - TSynCustomHighlighter.IsIdentChar()

### ISSUE THREAD

**Issue by JaFi-cz** [TurboPack/SynEdit#59]
Acording to last change I want to suggest change:
SyneditHighlighter.pas, line 1073

Current code:
```
function TSynCustomHighlighter.IsIdentChar(AChar: WideChar): Boolean;
begin
  case AChar of
    '_', '0'..'9', 'A'..'Z', 'a'..'z':
      Result := True;
    else
      Result := False;
  end;
  Result := Result or CharInSet(AChar, FAdditionalIdentChars);
  Result := Result and not IsWordBreakChar(AChar);
end;
```
Suggested change:
```
function TSynCustomHighlighter.IsIdentChar(AChar: WideChar): Boolean;
begin
  Result := IsCharAlphaNumeric(AChar) or CharInSet(AChar, ['_', '-']);          
  Result := Result or CharInSet(AChar, FAdditionalIdentChars);
  Result := Result and not IsWordBreakChar(AChar);
end;
```

Maybe you find it strange, but some programming languages allows you to use accented chars in function names e.t.c.

**Comment by pyscripter** [comment]
Interesting suggestion but:
- Most languages do not support non-ascii identifiers.
- '-' is not a valid identifier character in many languages.
- The method is virtual and can be overwritten by specific highlighters.

In my SynPythonSyn implementation I am going to simply use:

`if AChar = '_' or AChar.IsLetterOrDigit
`

AChr.IsLetterOrDigit is I think Equivalent to Windows.IsCharAlphaNumeric(AChar)

because
