### ISSUE TITLE
sqlOracle Dialect bug 

### ISSUE THREAD

**Issue by dados** [TurboPack/SynEdit#60]
Try setting the dialect to sqlOracle and set some colors for below properies
  OracleCommentKW: string = 'REM,REMA,REMAR,REMARK';
  OracleConsoleOutputKW: string = 'PRO,PROM,PROMP,PROMPT';

for example:
select **pro.description, users.id**
from some_table **pro, users_table users**
  
The bold text is regarded as an OracleConsoleOutput....and thats just wrong
The same can be produced for OracleCommentKW
![sqlOracleHighlighterBug](https://user-images.githubusercontent.com/410581/119000772-f0152b80-b97a-11eb-8207-1b6e4dea04df.png)

**Comment by pyscripter** [comment]
@JaFi-cz Could you please comment on this?

**Comment by JaFi-cz** [comment]
I use my own old version of the SynHighlighterSQL.PAS, cause this one what cames with Synedit is strange. 
Just now I am in phase to make it CodeFolding ready.

What I can do is download this unit and check it.

**Comment by JaFi-cz** [comment]
On the first quick look, 
procedure TSynSQLSyn.IdentProc;   (line 1590)
is strange.

coloring depends of the fTokenID, the content of procedure starts with:
  fTokenID := IdentKind((fLine + Run));

**Comment by JaFi-cz** [comment]
I just examinated your examples.
Synedit isn't advanced language evaluator and parser, synedit simple highlights text file based on rules in highlighter.

The rule definitions for Oracle:
if there is console output keyword, rest of the line is highlighted as console output
if there is comment keyword, rest of the line is highlighted as comment

If you use keywords as table alias, it will follow rules and highlight it as defined.
Highlighter doesn't know if you are in SELECT/DELETE/UPDATE command or in the content of stored procedure or ... The implementation of it isn't impossible, but very dificult, because you don't recognize end of command easily. You can have subselects, union of selects in one TSQL command.
And SQL highlighter isn't for Oracle or PL/SQL only, but for about tens of other SQL dialects.

The simpliest way is not use keywords as table alias. Same as you can't use keywords for name of columns, tables or aliases directly, don't use another keywords too.

example of nonsence TSQL command
```
select delete.between, delete.and
  from update delete
  join table outer on delete.ID = outer.ID
```
You can workarround it with enclosing names in brackets but it's way to the hell.

**Comment by pyscripter** [comment]
@JaFi-cz should we close this?

**Comment by JaFi-cz** [comment]
Yes. 
I don't see nothing wrong in highlighter. Problem is conflict PL/SQL keywords used in SQL statement.
