### ISSUE TITLE
DoBlockUnindent issues

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#87]
There appears to be a problem with DoBlockUnindent.  If more than one line is selected and this is called (in my case via Shift-Tab) an access violation occurs.

Also if Shift-Tab is pressed without a selection while the caret is at the end of a line it deletes the prior characters in mulltiples of TabSize.  This seems odd (older versions do this, I just never noticed it.)

-Mark

**Comment by MShark67** [comment]
In DoBlockUnindent there's a line:
`        StrToDelete := Run;
`
I think it needs to be something like:
`
StrLCopy(StrToDelete, Run, StrToDeleteLen -1);
`
-Mark

**Comment by pyscripter** [comment]
I know how to fix the error, but I am currently refactoring DoBlockUnIndent,  this is why it is taking time.

On the other hand DoShiftTabKey in combination with eoSmartTabls is seriously broken (has always been) and I will try to fix that as well.

Did you try the fixes for #83?

**Comment by MShark67** [comment]
I did test #83 and it seems to work perfectly.  Great work!

-Mark

**Comment by pyscripter** [comment]
Fixed both the exception on Block Unindent and the Shift Tab Smart Tabs issue.
Refactored Block Indent/Unindent.
Minor Breaking Change (removed eoSmartTabs from default options and added eoTabIndent

I have changed the default options, since SmartTabs does not make much sense in code editors (except when editing tabular data files) whilst Tab(Block) Indent is a must. 

@MShark67 Please check both issues.

**Comment by MShark67** [comment]
Looks great and performance is very good on huge files.  There's a possible minor issue when Shift-Tab is used where no indent exists.  It seems that it adds an entry to the undo list even though no apparent change occurred.
I completely agree on the default options change.

**Comment by pyscripter** [comment]
@MShark67 
The "minor issue" is fixed in https://github.com/TurboPack/SynEdit/commit/2cbfc68cbd9b3628f876a2008dd18c46e81149c8
