### ISSUE TITLE
Update scrollbars issue

### ISSUE THREAD

**Issue by MShark67** [TurboPack/SynEdit#97]
It seems that some actions don't update or refresh the scrollbars.  Examples include calling Clear, setting the Text property, and toggling the wordwrap property.  This is not a new issue as I noticed that in my code I'm toggling the scrollbar property to none and then back to the original setting to fix the issue.

**Comment by pyscripter** [comment]
Is this the cause 35dfc8c7baaf80e8b1920cbddc92f399a6283f80?

**Comment by MShark67** [comment]
No, it's unrelated to that change and has been the case for a while.

**Comment by pyscripter** [comment]
I can replicate with Clear.  
If you add 
  UpdateScrollbars;
at the end of ClearAll that works.

I can reproduce it also with changing the Text.  The solution is similar.

I cannot reproduce this with setting the Wordwrap to True.  SetWordWrap always calls UpdateScrollbar.


Explanations regarding this issue:

It the original SynEdit the UpdateScrollbar was always called in LinesChanged and in SetCaretXYEx.   This was causing a massive amount of flicker.   You only need to update the scrollbars if needed.

-  SetCaretXYEx already calls EnsurePosVisible which updates the TopLine and LeftChar if needed which in turn update the Scrollbar.
- SetCaretXYEx also calls Inc/DecPaintLock.  PaintLock calls UpdateScrollBars if sfScrollbarChanged is in fStateFlags.
- Instead of calling always UpdateScrllbar in LinesChanges sfScrollbarChanged is set when lines are added or deleted but not when a line is changed.

**Comment by MShark67** [comment]
Adding UpdateScrollbar to ClearAll and SynSetText resolves it, thanks!  I'm not seeing the issue with wordwrap, so perhaps I was just mistaken on that (or my code additions were from an earlier version.) Totally agreed and understood on the flicker reduction, that's all good stuff!
